Update git version, optimize for gitbuild type and refactor builds

diff --git a/.ansible/DOCKERFILES/Dockerfile-prod.j2 b/.ansible/DOCKERFILES/Dockerfile-prod.j2
--- a/.ansible/DOCKERFILES/Dockerfile-prod.j2
+++ b/.ansible/DOCKERFILES/Dockerfile-prod.j2
@@ -27,30 +27,30 @@ LABEL "org.opencontainers.image.description"="PHP-FPM {{ php_version }}-prod"
 ### Install
 ###
 RUN set -eux \
-	&& DEBIAN_FRONTEND=noninteractive apt-get update \
-	&& DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-install-suggests \
-		locales-all \
-		postfix \
-		postfix-pcre \
-		cron \
-		rsyslog \
-		socat \
-		supervisor \
-	&& rm -rf /var/lib/apt/lists/* \
-	\
+    && DEBIAN_FRONTEND=noninteractive apt-get update \
+    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-install-suggests \
+        locales-all \
+        postfix \
+        postfix-pcre \
+        cron \
+        rsyslog \
+        socat \
+        supervisor \
+    && rm -rf /var/lib/apt/lists/* \
+    \
 # Fix: rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
-	&& sed -i''  's/.*imklog.*//g' /etc/rsyslog.conf \
-	\
+    && sed -i''  's/.*imklog.*//g' /etc/rsyslog.conf \
+    \
 # Setup Supervisor
-	&& rm -rf /etc/supervisor* \
-	&& mkdir -p /var/log/supervisor \
-	&& mkdir -p /etc/supervisor/conf.d \
-	&& mkdir -p /etc/supervisor/custom.d \
-	&& chown devilbox:devilbox /etc/supervisor/custom.d \
-	\
-	&& (find /usr/local/bin  -type f -print0 | xargs -n1 -0 -P$(getconf _NPROCESSORS_ONLN) strip --strip-all -p 2>/dev/null || true) \
-	&& (find /usr/local/lib  -type f -print0 | xargs -n1 -0 -P$(getconf _NPROCESSORS_ONLN) strip --strip-all -p 2>/dev/null || true) \
-	&& (find /usr/local/sbin -type f -print0 | xargs -n1 -0 -P$(getconf _NPROCESSORS_ONLN) strip --strip-all -p 2>/dev/null || true)
+    && rm -rf /etc/supervisor* \
+    && mkdir -p /var/log/supervisor \
+    && mkdir -p /etc/supervisor/conf.d \
+    && mkdir -p /etc/supervisor/custom.d \
+    && chown devilbox:devilbox /etc/supervisor/custom.d \
+    \
+    && (find /usr/local/bin  -type f -print0 | xargs -n1 -0 -P$(getconf _NPROCESSORS_ONLN) strip --strip-all -p 2>/dev/null || true) \
+    && (find /usr/local/lib  -type f -print0 | xargs -n1 -0 -P$(getconf _NPROCESSORS_ONLN) strip --strip-all -p 2>/dev/null || true) \
+    && (find /usr/local/sbin -type f -print0 | xargs -n1 -0 -P$(getconf _NPROCESSORS_ONLN) strip --strip-all -p 2>/dev/null || true)
 
 
 {% if debug %}
@@ -58,20 +58,20 @@ RUN set -eux \
 ### Verify
 ###
 RUN set -eux \
-	&& echo "date.timezone=UTC" > /usr/local/etc/php/php.ini \
-	&& php -v | grep -oE 'PHP\s[.0-9]+' | grep -oE '[.0-9]+' | grep '^{{ php_version }}' \
-	&& /usr/local/sbin/php-fpm --test \
-	\
-	&& PHP_ERROR="$( php -v 2>&1 1>/dev/null )" \
-	&& if [ -n "${PHP_ERROR}" ]; then echo "${PHP_ERROR}"; false; fi \
-	&& PHP_ERROR="$( php -i 2>&1 1>/dev/null )" \
-	&& if [ -n "${PHP_ERROR}" ]; then echo "${PHP_ERROR}"; false; fi \
-	\
-	&& PHP_FPM_ERROR="$( php-fpm -v 2>&1 1>/dev/null )" \
-	&& if [ -n "${PHP_FPM_ERROR}" ]; then echo "${PHP_FPM_ERROR}"; false; fi \
-	&& PHP_FPM_ERROR="$( php-fpm -i 2>&1 1>/dev/null )" \
-	&& if [ -n "${PHP_FPM_ERROR}" ]; then echo "${PHP_FPM_ERROR}"; false; fi \
-	&& rm -f /usr/local/etc/php/php.ini
+    && echo "date.timezone=UTC" > /usr/local/etc/php/php.ini \
+    && php -v | grep -oE 'PHP\s[.0-9]+' | grep -oE '[.0-9]+' | grep '^{{ php_version }}' \
+    && /usr/local/sbin/php-fpm --test \
+    \
+    && PHP_ERROR="$( php -v 2>&1 1>/dev/null )" \
+    && if [ -n "${PHP_ERROR}" ]; then echo "${PHP_ERROR}"; false; fi \
+    && PHP_ERROR="$( php -i 2>&1 1>/dev/null )" \
+    && if [ -n "${PHP_ERROR}" ]; then echo "${PHP_ERROR}"; false; fi \
+    \
+    && PHP_FPM_ERROR="$( php-fpm -v 2>&1 1>/dev/null )" \
+    && if [ -n "${PHP_FPM_ERROR}" ]; then echo "${PHP_FPM_ERROR}"; false; fi \
+    && PHP_FPM_ERROR="$( php-fpm -i 2>&1 1>/dev/null )" \
+    && if [ -n "${PHP_FPM_ERROR}" ]; then echo "${PHP_FPM_ERROR}"; false; fi \
+    && rm -f /usr/local/etc/php/php.ini
 
 
 {% endif %}
diff --git a/Dockerfiles/slim/Dockerfile-8.2 b/Dockerfiles/slim/Dockerfile-8.2
--- a/Dockerfiles/slim/Dockerfile-8.2
+++ b/Dockerfiles/slim/Dockerfile-8.2
@@ -18,20 +18,20 @@ FROM devilboxcommunity/php-fpm:8.2-prod as devilbox-slim-base-builder
 ### Install apt Tools
 ###
 RUN set -eux \
-	&& DEBIAN_FRONTEND=noninteractive apt-get update \
-	&& DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-install-suggests \
-		apt-transport-https \
-		ca-certificates \
-		curl \
-		dirmngr \
-		gnupg
+    && DEBIAN_FRONTEND=noninteractive apt-get update \
+    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-install-suggests \
+        apt-transport-https \
+        ca-certificates \
+        curl \
+        dirmngr \
+        gnupg
 
 ###
 ### Add apt repositories
 ###
 RUN set -eux \
 	&& apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138	\
-	&& echo "deb http://ftp.debian.org/debian bullseye-backports main" > /etc/apt/sources.list.d/backports.list \
+	&& echo "deb http://ftp.debian.org/debian bookworm-backports main contrib non-free" > /etc/apt/sources.list.d/backports.list \
 	&& curl -sS -L --fail "https://packages.blackfire.io/gpg.key" | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 apt-key add -	\
 	&& echo "deb http://packages.blackfire.io/debian any main" > /etc/apt/sources.list.d/blackfire.list \
 	&& true
@@ -40,28 +40,28 @@ RUN set -eux \
 ### Install build_dep
 ###
 RUN set -eux \
-	&& DEBIAN_FRONTEND=noninteractive apt-get update \
-	&& DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-install-suggests \
-		libsnappy-dev \
-	&& rm -rf /var/lib/apt/lists/*
+    && DEBIAN_FRONTEND=noninteractive apt-get update \
+    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-install-suggests \
+        libsnappy-dev \
+    && rm -rf /var/lib/apt/lists/*
 ###
 ### Add common tools
 ###
 RUN set -eux \
-	&& DEBIAN_FRONTEND=noninteractive apt-get update \
-	&& DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-install-suggests \
-		file \
-		git \
-		mariadb-client \
-		redis-tools \
-		sqlite3
+    && DEBIAN_FRONTEND=noninteractive apt-get update \
+    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-install-suggests \
+        file \
+        git \
+        mariadb-client \
+        redis-tools \
+        sqlite3
 
 ###
 ### Install tools type: apt
 ###
 RUN set -eux \
-	&& DEBIAN_FRONTEND=noninteractive apt-get update \
-	&& DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-install-suggests \
+    && DEBIAN_FRONTEND=noninteractive apt-get update \
+    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-install-suggests \
 		# ---------- type: apt ----------
 		dnsutils \
 		iputils-ping \
@@ -124,7 +124,7 @@ RUN set -eux \
 # -------------------- mongo_client --------------------
 RUN set -eux \
 	&& APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 20691EEC35216C63CAF66CE1656408E390CFB1F5 \
-	&& echo "deb http://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" > /etc/apt/sources.list.d/mongo.list \
+	&& echo "deb http://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/4.4 multiverse" > /etc/apt/sources.list.d/mongo.list \
 	&& apt-get update \
 	\
 	&& apt-get install -y --no-install-recommends --no-install-suggests \
@@ -179,7 +179,7 @@ RUN set -eux \
 # -------------------- pgsql_client --------------------
 RUN set -eux \
 	&& curl -sS -k -L --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 apt-key add - \
-	&& echo "deb http://apt.postgresql.org/pub/repos/apt/ bullseye-pgdg main" > /etc/apt/sources.list.d/pgsql.list \
+	&& echo "deb http://apt.postgresql.org/pub/repos/apt/ bookworm-pgdg main" > /etc/apt/sources.list.d/pgsql.list \
 	&& apt-get update \
 	\
 	&& apt-get install -y --no-install-recommends --no-install-suggests \
@@ -200,36 +200,36 @@ RUN set -eux \
 ### Prepare required shared libraries for copying (keep symlinks)
 ###
 RUN set -eux \
-	&& LIB_GNU_DIR="/lib/$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \
-	&& USR_LIB_DIR="/usr/lib" \
-	&& USR_LIB_GNU_DIR="/usr/lib/$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \
-	\
-	&& mkdir /tmp/lib-gnu \
-	&& mkdir /tmp/usr-lib \
-	&& mkdir /tmp/usr-lib-gnu \
-	\
-	&& LIB_GNU="libreadline" \
-	&& USR_LIB="libsnappy libtcmalloc libv8" \
-	&& USR_LIB_GNU="liblua libpq libpcrecpp libboost libjemalloc libunwind libhiredis libedit libyaml-cpp libstemmer libsnappy libpcap libbsd liblzf" \
-	\
-	&& for lib in ${LIB_GNU}; do \
-		if ls -1 "${LIB_GNU_DIR}/" | grep "^${lib}" >/dev/null; then \
-			echo "Coping '${lib}' from: ${LIB_GNU_DIR}"; \
-			cp -r ${LIB_GNU_DIR}/${lib}* /tmp/lib-gnu/; \
-		fi \
-	done \
-	&& for lib in ${USR_LIB}; do \
-		if ls -1 "${USR_LIB_DIR}/" | grep "^${lib}" >/dev/null; then \
-			echo "Coping '${lib}' from: ${USR_LIB_DIR}"; \
-			cp -r ${USR_LIB_DIR}/${lib}* /tmp/usr-lib/; \
-		fi \
-	done \
-	&& for lib in ${USR_LIB_GNU}; do \
-		if ls -1 "${USR_LIB_GNU_DIR}/" | grep "^${lib}" >/dev/null; then \
-			echo "Coping '${lib}' from: ${USR_LIB_GNU_DIR}"; \
-			cp -r ${USR_LIB_GNU_DIR}/${lib}* /tmp/usr-lib-gnu/; \
-		fi \
-	done
+    && LIB_GNU_DIR="/lib/$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \
+    && USR_LIB_DIR="/usr/lib" \
+    && USR_LIB_GNU_DIR="/usr/lib/$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \
+    \
+    && mkdir /tmp/lib-gnu \
+    && mkdir /tmp/usr-lib \
+    && mkdir /tmp/usr-lib-gnu \
+    \
+    && LIB_GNU="libreadline" \
+    && USR_LIB="libsnappy libtcmalloc libv8" \
+    && USR_LIB_GNU="liblua libpq libpcrecpp libboost libjemalloc libunwind libhiredis libedit libyaml-cpp libstemmer libsnappy libpcap libbsd liblzf" \
+    \
+    && for lib in ${LIB_GNU}; do \
+        if ls -1 "${LIB_GNU_DIR}/" | grep "^${lib}" >/dev/null; then \
+            echo "Coping '${lib}' from: ${LIB_GNU_DIR}"; \
+            cp -r ${LIB_GNU_DIR}/${lib}* /tmp/lib-gnu/; \
+        fi \
+    done \
+    && for lib in ${USR_LIB}; do \
+        if ls -1 "${USR_LIB_DIR}/" | grep "^${lib}" >/dev/null; then \
+            echo "Coping '${lib}' from: ${USR_LIB_DIR}"; \
+            cp -r ${USR_LIB_DIR}/${lib}* /tmp/usr-lib/; \
+        fi \
+    done \
+    && for lib in ${USR_LIB_GNU}; do \
+        if ls -1 "${USR_LIB_GNU_DIR}/" | grep "^${lib}" >/dev/null; then \
+            echo "Coping '${lib}' from: ${USR_LIB_GNU_DIR}"; \
+            cp -r ${USR_LIB_GNU_DIR}/${lib}* /tmp/usr-lib-gnu/; \
+        fi \
+    done
 
 ###
 ### Fix expected PostgreSQL directories
@@ -238,12 +238,12 @@ RUN set -eux \
 ### but they are still needed to be present, so we can copy them.
 ###
 RUN set -eux \
-	&& if [ ! -d "/usr/lib/postgresql" ]; then \
-		mkdir "/usr/lib/postgresql"; \
-	fi \
-	&& if [ ! -d "/usr/share/postgresql-common" ]; then \
-		mkdir "/usr/share/postgresql-common"; \
-	fi
+    && if [ ! -d "/usr/lib/postgresql" ]; then \
+        mkdir "/usr/lib/postgresql"; \
+    fi \
+    && if [ ! -d "/usr/share/postgresql-common" ]; then \
+        mkdir "/usr/share/postgresql-common"; \
+    fi
 
 ###
 ### Prepare MongoDB binaries for copying.
@@ -251,36 +251,36 @@ RUN set -eux \
 ### They might not be available on all architectures (e.g.: arm64).
 ###
 RUN set -eux \
-	&& mkdir /tmp/mongo \
-	&& if ls -1 "/usr/bin/" | grep "^mongo" >/dev/null; then \
-		cp -r /usr/bin/mongo* /tmp/mongo/; \
-	fi
+    && mkdir /tmp/mongo \
+    && if ls -1 "/usr/bin/" | grep "^mongo" >/dev/null; then \
+        cp -r /usr/bin/mongo* /tmp/mongo/; \
+    fi
 
 ###
 ### Strip debugging information to smallen filesize
 ###
 RUN set -eux \
-	&& STRIP_USR_BINS="blackfire mongo mysql redis sqlite" \
-	&& STRIP_DIRS="/usr/lib/postgresql/ /usr/share/postgresql-common/ /tmp" \
-	\
-	&& for bin in ${STRIP_USR_BINS}; do \
-		( \
-			find /usr/bin/ -name "${bin}"* -type f -print0 \
-			| xargs -n1 -0 -P$(getconf _NPROCESSORS_ONLN) sh -c \
-				'if [ -f "${1}" ]; then echo "Strip: ${1}"; strip --strip-all -p "${1}" 2>/dev/null || true; fi' -- \
-		) \
-	done \
-	\
-	&& for dir in ${STRIP_DIRS}; do \
-		( \
-			find ${dir} -type f -print0 \
-			| xargs -n1 -0 -P$(getconf _NPROCESSORS_ONLN) sh -c \
-				'if [ -f "${1}" ]; then echo "Strip: ${1}"; strip --strip-all -p "${1}" 2>/dev/null || true; fi' -- \
-		) \
-	done \
-	\
-	&& strip --strip-all -p /usr/local/bin/mhsendmail 2>/dev/null || true \
-	&& strip --strip-all -p /usr/local/bin/mysqldump-secure 2>/dev/null || true
+    && STRIP_USR_BINS="blackfire mongo mysql redis sqlite" \
+    && STRIP_DIRS="/usr/lib/postgresql/ /usr/share/postgresql-common/ /tmp" \
+    \
+    && for bin in ${STRIP_USR_BINS}; do \
+        ( \
+            find /usr/bin/ -name "${bin}"* -type f -print0 \
+            | xargs -n1 -0 -P$(getconf _NPROCESSORS_ONLN) sh -c \
+                'if [ -f "${1}" ]; then echo "Strip: ${1}"; strip --strip-all -p "${1}" 2>/dev/null || true; fi' -- \
+        ) \
+    done \
+    \
+    && for dir in ${STRIP_DIRS}; do \
+        ( \
+            find ${dir} -type f -print0 \
+            | xargs -n1 -0 -P$(getconf _NPROCESSORS_ONLN) sh -c \
+                'if [ -f "${1}" ]; then echo "Strip: ${1}"; strip --strip-all -p "${1}" 2>/dev/null || true; fi' -- \
+        ) \
+    done \
+    \
+    && strip --strip-all -p /usr/local/bin/mhsendmail 2>/dev/null || true \
+    && strip --strip-all -p /usr/local/bin/mysqldump-secure 2>/dev/null || true
 
 
 
@@ -302,8 +302,8 @@ ARG ARCH
 ### Install tools type: apt
 ###
 RUN set -eux \
-	&& DEBIAN_FRONTEND=noninteractive apt-get update \
-	&& DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-install-suggests \
+    && DEBIAN_FRONTEND=noninteractive apt-get update \
+    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-install-suggests \
 		# ---------- type: apt ----------
 		dnsutils \
 		iputils-ping \
@@ -367,28 +367,28 @@ COPY --from=devilbox-slim-base-builder /usr/share/perl5 /usr/share/perl5
 ### Create PostgreSQL symlinks
 ###
 RUN set -eux \
-	&& if [ -f "/usr/share/postgresql-common/pg_wrapper" ]; then \
-		ln -s ../share/postgresql-common/pg_wrapper /usr/bin/clusterdb \
-		&& ln -s ../share/postgresql-common/pg_wrapper /usr/bin/createdb \
-		&& ln -s ../share/postgresql-common/pg_wrapper /usr/bin/createlang \
-		&& ln -s ../share/postgresql-common/pg_wrapper /usr/bin/createuser \
-		&& ln -s ../share/postgresql-common/pg_wrapper /usr/bin/dropdb \
-		&& ln -s ../share/postgresql-common/pg_wrapper /usr/bin/droplang \
-		&& ln -s ../share/postgresql-common/pg_wrapper /usr/bin/dropuser \
-		&& ln -s ../share/postgresql-common/pg_wrapper /usr/bin/pg_basebackup \
-		&& ln -s ../share/postgresql-common/pg_wrapper /usr/bin/pg_dump \
-		&& ln -s ../share/postgresql-common/pg_wrapper /usr/bin/pg_dumpall \
-		&& ln -s ../share/postgresql-common/pg_wrapper /usr/bin/pg_isready \
-		&& ln -s ../share/postgresql-common/pg_wrapper /usr/bin/pg_receivewal \
-		&& ln -s ../share/postgresql-common/pg_wrapper /usr/bin/pg_receivexlog \
-		&& ln -s ../share/postgresql-common/pg_wrapper /usr/bin/pg_recvlogical \
-		&& ln -s ../share/postgresql-common/pg_wrapper /usr/bin/pg_restore \
-		&& ln -s ../share/postgresql-common/pg_wrapper /usr/bin/pgbench \
-		&& ln -s ../share/postgresql-common/pg_wrapper /usr/bin/psql \
-		&& ln -s ../share/postgresql-common/pg_wrapper /usr/bin/reindexdb \
-		&& ln -s ../share/postgresql-common/pg_wrapper /usr/bin/vacuumdb \
-		&& ln -s ../share/postgresql-common/pg_wrapper /usr/bin/vacuumlo; \
-	fi
+    && if [ -f "/usr/share/postgresql-common/pg_wrapper" ]; then \
+        ln -s ../share/postgresql-common/pg_wrapper /usr/bin/clusterdb \
+        && ln -s ../share/postgresql-common/pg_wrapper /usr/bin/createdb \
+        && ln -s ../share/postgresql-common/pg_wrapper /usr/bin/createlang \
+        && ln -s ../share/postgresql-common/pg_wrapper /usr/bin/createuser \
+        && ln -s ../share/postgresql-common/pg_wrapper /usr/bin/dropdb \
+        && ln -s ../share/postgresql-common/pg_wrapper /usr/bin/droplang \
+        && ln -s ../share/postgresql-common/pg_wrapper /usr/bin/dropuser \
+        && ln -s ../share/postgresql-common/pg_wrapper /usr/bin/pg_basebackup \
+        && ln -s ../share/postgresql-common/pg_wrapper /usr/bin/pg_dump \
+        && ln -s ../share/postgresql-common/pg_wrapper /usr/bin/pg_dumpall \
+        && ln -s ../share/postgresql-common/pg_wrapper /usr/bin/pg_isready \
+        && ln -s ../share/postgresql-common/pg_wrapper /usr/bin/pg_receivewal \
+        && ln -s ../share/postgresql-common/pg_wrapper /usr/bin/pg_receivexlog \
+        && ln -s ../share/postgresql-common/pg_wrapper /usr/bin/pg_recvlogical \
+        && ln -s ../share/postgresql-common/pg_wrapper /usr/bin/pg_restore \
+        && ln -s ../share/postgresql-common/pg_wrapper /usr/bin/pgbench \
+        && ln -s ../share/postgresql-common/pg_wrapper /usr/bin/psql \
+        && ln -s ../share/postgresql-common/pg_wrapper /usr/bin/reindexdb \
+        && ln -s ../share/postgresql-common/pg_wrapper /usr/bin/vacuumdb \
+        && ln -s ../share/postgresql-common/pg_wrapper /usr/bin/vacuumlo; \
+    fi
 
 ###
 ### Copy Redis Client
@@ -419,26 +419,26 @@ COPY ./data/sudo-devilbox /etc/sudoers.d/devilbox
 ### Configure Bash
 ###
 RUN set -eux \
-	&& { \
-		echo; \
-		echo "# [Devilbox] Ensure /usr/local(s)?bin is in PATH"; \
-		echo 'PATH="${PATH}:/usr/local/bin:/usr/local/sbin"'; \
-		echo "export PATH"; \
-		echo; \
-		echo "# [Devilbox] Source Devilbox main bash config"; \
-		echo ". /etc/bash-devilbox"; \
-		echo; \
-		echo "# [Devilbox] Source Devilbox custom configs"; \
-		echo "if [ -d /etc/bashrc-devilbox.d/ ]; then"; \
-		echo "    for f in /etc/bashrc-devilbox.d/*.sh ; do"; \
-		echo "        if [ -r \"\${f}\" ]; then"; \
-		echo "            . \"\${f}\""; \
-		echo "        fi"; \
-		echo "    done"; \
-		echo "    unset f"; \
-		echo "fi"; \
-	} | tee -a /home/${MY_USER}/.bashrc /root/.bashrc \
-	&& chown ${MY_USER}:${MY_GROUP} /home/${MY_USER}/.bashrc
+    && { \
+        echo; \
+        echo "# [Devilbox] Ensure /usr/local(s)?bin is in PATH"; \
+        echo 'PATH="${PATH}:/usr/local/bin:/usr/local/sbin"'; \
+        echo "export PATH"; \
+        echo; \
+        echo "# [Devilbox] Source Devilbox main bash config"; \
+        echo ". /etc/bash-devilbox"; \
+        echo; \
+        echo "# [Devilbox] Source Devilbox custom configs"; \
+        echo "if [ -d /etc/bashrc-devilbox.d/ ]; then"; \
+        echo "    for f in /etc/bashrc-devilbox.d/*.sh ; do"; \
+        echo "        if [ -r \"\${f}\" ]; then"; \
+        echo "            . \"\${f}\""; \
+        echo "        fi"; \
+        echo "    done"; \
+        echo "    unset f"; \
+        echo "fi"; \
+    } | tee -a /home/${MY_USER}/.bashrc /root/.bashrc \
+    && chown ${MY_USER}:${MY_GROUP} /home/${MY_USER}/.bashrc
 
 
 
@@ -455,9 +455,9 @@ RUN set -eux \
 ###
 FROM devilbox-slim-base as devilbox-slim-base-test
 RUN set -eux \
-	&& mysql --version \
-	&& redis-cli --version \
-	&& sqlite3 --version
+    && mysql --version \
+    && redis-cli --version \
+    && sqlite3 --version
 
 ###
 ### Check if available tools slim
@@ -536,34 +536,34 @@ RUN set -eux \
 ### Re-activate modules which have been deactivated in mods (for testing).
 ###
 RUN set -eux \
-	&& if find /usr/local/lib/php/extensions/ -name phalcon.so | grep phalcon; then \
-		echo "extension=phalcon.so" > /usr/local/etc/php/conf.d/docker-php-ext-phalcon.ini; \
-	fi \
-	&& if find /usr/local/lib/php/extensions/ -name psr.so | grep psr; then \
-		echo "extension=psr.so" > /usr/local/etc/php/conf.d/docker-php-ext-psr.ini; \
-	fi \
-	&& if find /usr/local/lib/php/extensions/ -name xhprof.so | grep xhprof; then \
-		echo "extension=xhprof.so" > /usr/local/etc/php/conf.d/docker-php-ext-xhprof.ini; \
-	fi
+    && if find /usr/local/lib/php/extensions/ -name phalcon.so | grep phalcon; then \
+        echo "extension=phalcon.so" > /usr/local/etc/php/conf.d/docker-php-ext-phalcon.ini; \
+    fi \
+    && if find /usr/local/lib/php/extensions/ -name psr.so | grep psr; then \
+        echo "extension=psr.so" > /usr/local/etc/php/conf.d/docker-php-ext-psr.ini; \
+    fi \
+    && if find /usr/local/lib/php/extensions/ -name xhprof.so | grep xhprof; then \
+        echo "extension=xhprof.so" > /usr/local/etc/php/conf.d/docker-php-ext-xhprof.ini; \
+    fi
 
 ###
 ### Check if PHP still works
 ###
 RUN set -eux \
-	&& echo "date.timezone=UTC" > /usr/local/etc/php/php.ini \
-	&& php -v | grep -oE 'PHP\s[.0-9]+' | grep -oE '[.0-9]+' | grep '^8.2' \
-	&& /usr/local/sbin/php-fpm --test \
-	\
-	&& PHP_ERROR="$( php -v 2>&1 1>/dev/null )" \
-	&& if [ -n "${PHP_ERROR}" ]; then echo "${PHP_ERROR}"; false; fi \
-	&& PHP_ERROR="$( php -i 2>&1 1>/dev/null )" \
-	&& if [ -n "${PHP_ERROR}" ]; then echo "${PHP_ERROR}"; false; fi \
-	\
-	&& PHP_FPM_ERROR="$( php-fpm -v 2>&1 1>/dev/null )" \
-	&& if [ -n "${PHP_FPM_ERROR}" ]; then echo "${PHP_FPM_ERROR}"; false; fi \
-	&& PHP_FPM_ERROR="$( php-fpm -i 2>&1 1>/dev/null )" \
-	&& if [ -n "${PHP_FPM_ERROR}" ]; then echo "${PHP_FPM_ERROR}"; false; fi \
-	&& rm -f /usr/local/etc/php/php.ini
+    && echo "date.timezone=UTC" > /usr/local/etc/php/php.ini \
+    && php -v | grep -oE 'PHP\s[.0-9]+' | grep -oE '[.0-9]+' | grep '^8.2' \
+    && /usr/local/sbin/php-fpm --test \
+    \
+    && PHP_ERROR="$( php -v 2>&1 1>/dev/null )" \
+    && if [ -n "${PHP_ERROR}" ]; then echo "${PHP_ERROR}"; false; fi \
+    && PHP_ERROR="$( php -i 2>&1 1>/dev/null )" \
+    && if [ -n "${PHP_ERROR}" ]; then echo "${PHP_ERROR}"; false; fi \
+    \
+    && PHP_FPM_ERROR="$( php-fpm -v 2>&1 1>/dev/null )" \
+    && if [ -n "${PHP_FPM_ERROR}" ]; then echo "${PHP_FPM_ERROR}"; false; fi \
+    && PHP_FPM_ERROR="$( php-fpm -i 2>&1 1>/dev/null )" \
+    && if [ -n "${PHP_FPM_ERROR}" ]; then echo "${PHP_FPM_ERROR}"; false; fi \
+    && rm -f /usr/local/etc/php/php.ini
 
 
 
@@ -579,7 +579,7 @@ RUN set -eux \
 ### Prepare final base image (STAGE: slim)
 ###
 FROM devilbox-slim-base as slim
-MAINTAINER "cytopia" <cytopia@everythingcli.org>
+MAINTAINER "Toan Nguyen" <devilbox@nntoan.com>
 
 ###
 ### Labels
@@ -588,11 +588,11 @@ MAINTAINER "cytopia" <cytopia@everythingcli.org>
 #LABEL "org.opencontainers.image.created"=""
 #LABEL "org.opencontainers.image.version"=""
 #LABEL "org.opencontainers.image.revision"=""
-LABEL "maintainer"="cytopia <cytopia@everythingcli.org>"
-LABEL "org.opencontainers.image.authors"="cytopia <cytopia@everythingcli.org>"
-LABEL "org.opencontainers.image.url"="https://github.com/devilbox/docker-php-fpm"
-LABEL "org.opencontainers.image.documentation"="https://github.com/devilbox/docker-php-fpm"
-LABEL "org.opencontainers.image.source"="https://github.com/devilbox/docker-php-fpm"
+LABEL "maintainer"="Toan Nguyen <devilbox@nntoan.com>"
+LABEL "org.opencontainers.image.authors"="cytopia <cytopia@everythingcli.org>, Toan Nguyen <devilbox@nntoan.com>"
+LABEL "org.opencontainers.image.url"="https://github.com/devilbox-community/docker-php-fpm"
+LABEL "org.opencontainers.image.documentation"="https://github.com/devilbox-community/docker-php-fpm"
+LABEL "org.opencontainers.image.source"="https://github.com/devilbox-community/docker-php-fpm"
 LABEL "org.opencontainers.image.vendor"="devilbox"
 LABEL "org.opencontainers.image.licenses"="MIT"
 LABEL "org.opencontainers.image.ref.name"="8.2-slim"
